[build]
command = "npm install && npm run pages:build"
node_compat = true

[build.upload]
format = "modules"

[site]
bucket = ".vercel/output/static"

[env.production]
name = "podx-production"
node_compat = true

[env.preview]
name = "podx-preview"
node_compat = true

[compatibility_flags]
nodejs_compat = true 